---
- name: Ensure micro config directory exists
  ansible.builtin.file:
    path: "{{ dotfiles_home }}/.config/micro"
    state: directory
    mode: "0755"

- name: Install micro editor
  become: true
  ansible.builtin.apt:
    name: micro
    state: present

- name: Copy micro settings
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/../config/micro/settings.json"
    dest: "{{ dotfiles_home }}/.config/micro/settings.json"
    mode: "0644"
