---
- name: Ensure bashrc exists
  ansible.builtin.file:
    path: "{{ dotfiles_home }}/.bashrc"
    state: file
    mode: "0644"

- name: Manage shell block in bashrc
  ansible.builtin.blockinfile:
    path: "{{ dotfiles_home }}/.bashrc"
    marker: "# {mark} DOTFILES MANAGED BLOCK"
    block: "{{ shell_managed_block }}"

- name: Ensure github workspace exists
  ansible.builtin.file:
    path: "{{ dotfiles_home }}/github"
    state: directory
    mode: "0755"
