---
- name: Install WSL specific packages
  become: true
  ansible.builtin.apt:
    name:
      - linux-tools-generic
      - usbutils
      - wslu
    state: present

- name: Remove legacy dotfiles block from /etc/wsl.conf
  become: true
  ansible.builtin.blockinfile:
    path: /etc/wsl.conf
    create: true
    marker: "# {mark} DOTFILES WSL BLOCK"
    state: absent

- name: Ensure /etc/wsl.conf sets systemd
  become: true
  ansible.builtin.ini_file:
    path: /etc/wsl.conf
    create: true
    section: boot
    option: systemd
    value: "true"
